### ISSUE TITLE
Allow only CC or BCC recipients

### ISSUE THREAD

**Issue by inoda** [mailgun/mailgun-go#142]
Currently the validation in `messages.go` requires at least one recipient in the `to` field. However, I should be permitted to send an email as long as there is at least one recipient in the `to`, `cc`, OR `bcc` field.

**Comment by thrawn01** [comment]
I'll make this change in #149

**Comment by guilhermehubner** [comment]
@thrawn01 when do you intent to release v3?

**Comment by thrawn01** [comment]
@guilhermehubner I will tag the v3.0.0 release this week.

**Comment by guilhermehubner** [comment]
@thrawn01 I have tried: 

```go
        msg := client.NewMessage(defaultFrom, subject, "(html)")
	for _, email := range validRecipients {
		msg.AddBCC(email)
	}

	msg.SetHtml(htmlBody)
	if replyTo != "" {
		msg.AddHeader("Reply-To", replyTo)
	}

	_, _, err = m.client.Send(context.Background(), msg)
```

And got: 
```
[UnexpectedResponseError URL=https://api.mailgun.net/v3/***/messages 
ExpectedOneOf=[]int{200, 202, 204} Got=400 Error: {
  "message": "'to' parameter is missing"
}]
```

What is wrong?? I'm using v`3.3.0`

**Comment by thrawn01** [comment]
@guilhermehubner I'm chatting with the pipeline team to understand why `to` parameter is required. I'll let you know what I find out.

**Comment by thrawn01** [comment]
Hi @guilhermehubner I learned something new!

According to the team, you can use the `to` parameter multiple times. However doing this will include all the addresses given via the `to` parameter in the delivered emails`To:` header. I'm assuming you wish to avoid this which is why you are using the `bcc`. 

To solve for this, use the `to` parameter but include recipient variables for each address. It doesn't matter what the content of the variables are, as long as there are variables. Doing this mailgun will send the email with only the single address in the `To:` header of the delivered message.

```go
msg := client.NewMessage(defaultFrom, subject, "(html)")
for _, email := range validRecipients {
    msg.AddRecipientAndVariables(email, map[string]interface{}{email: true})
}

msg.SetHtml(htmlBody)
if replyTo != "" {
    msg.AddHeader("Reply-To", replyTo)
}

_, _, err = m.client.Send(context.Background(), msg)
```
See here for [batch sending](https://documentation.mailgun.com/en/latest/user_manual.html?highlight=batch%20sending#batch-sending) documentation

**Comment by guilhermehubner** [comment]
@thrawn01 it works! Thank you :grin:
