### ISSUE TITLE
GetUnsubscribes returns unsubscribes even after RemoveUnsubscribe called

### ISSUE THREAD

**Issue by johnnylee** [mailgun/mailgun-go#40]
I have a background process that periodically polls for unsubscribe events. I noticed in the log that it appears to be processing the same addresses each time it runs, even though I'm calling RemoveUnsubscribe with the unsubscribe events' IDs. 

Perhaps I'm doing something incorrectly, or I've misunderstood these calls. 

Any help is appreciated.

**Comment by johnnylee** [comment]
Also, the addresses no longer appear on the "Suppressions" tab on the web interface.

**Comment by r0mant** [comment]
Hi @johnnylee!

This behavior is expected due to the changes to the API introduced several months ago. You can read about it in this blog post: http://blog.mailgun.com/default-api-version-now-v3.

Basically, all our API libraries currently use API v2 under the hood. v2 version of the Suppressions API (bounces, unsubscribes, complaints) kept its request/response format for backward compatibility but effectively became an alias for the Events API (=logs) which is immutable.

Updating wrappers to API v3 is on our radar. Sorry about this confusion.

**Comment by johnnylee** [comment]
Is there a workaround to get the correct functionality? I don't want to unsubscribe addresses over and over again in our system. There will be circumstances where a user unsubscribes and the later subscribes again.
